# Site settings
title: Gavin's Notes 
description: "Gavin's Notes for recording important information , build with Jekyll."
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "gavin-k"
  email: "lijy0717@gmail.com"
  url: "http://gavin-k.github.io"

# Build settings
baseurl: /gavin-k.github.io/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "0.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
